import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <h1>Next JS Basic</h1>
      <hr/>
      {children}
      <hr/>
      <footer>
        <h3><Link href={"/"}>Back</Link></h3>
      </footer>
      </body>
    </html>
  );
}
